# Generated by Django 5.1.2 on 2024-11-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_recipe_deletion_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='kcal_per_100g',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='kcal_per_100g',
            field=models.PositiveIntegerField(),
        ),
    ]
