# Generated by Django 5.1.2 on 2024-11-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_ingredient_kcal_per_100g_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients_list',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='deletion_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
