# Generated by Django 5.1.2 on 2024-11-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_recipe_ingredients_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
