# Generated by Django 5.1.2 on 2024-11-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_friend_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='deletion_reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
